// Generated by gencpp from file hello_w/omegaResponse.msg
// DO NOT EDIT!


#ifndef HELLO_W_MESSAGE_OMEGARESPONSE_H
#define HELLO_W_MESSAGE_OMEGARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_w
{
template <class ContainerAllocator>
struct omegaResponse_
{
  typedef omegaResponse_<ContainerAllocator> Type;

  omegaResponse_()
    : angular(0.0)  {
    }
  omegaResponse_(const ContainerAllocator& _alloc)
    : angular(0.0)  {
  (void)_alloc;
    }



   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::hello_w::omegaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_w::omegaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct omegaResponse_

typedef ::hello_w::omegaResponse_<std::allocator<void> > omegaResponse;

typedef boost::shared_ptr< ::hello_w::omegaResponse > omegaResponsePtr;
typedef boost::shared_ptr< ::hello_w::omegaResponse const> omegaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_w::omegaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_w::omegaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_w

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::omegaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::omegaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::omegaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::omegaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::omegaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::omegaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_w::omegaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "960aa4f2aaeac14706e7fa1a905e8a00";
  }

  static const char* value(const ::hello_w::omegaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x960aa4f2aaeac147ULL;
  static const uint64_t static_value2 = 0x06e7fa1a905e8a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_w::omegaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_w/omegaResponse";
  }

  static const char* value(const ::hello_w::omegaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_w::omegaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angular\n"
"\n"
;
  }

  static const char* value(const ::hello_w::omegaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_w::omegaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct omegaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_w::omegaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_w::omegaResponse_<ContainerAllocator>& v)
  {
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_W_MESSAGE_OMEGARESPONSE_H
