// Generated by gencpp from file hello_w/omegaRequest.msg
// DO NOT EDIT!


#ifndef HELLO_W_MESSAGE_OMEGAREQUEST_H
#define HELLO_W_MESSAGE_OMEGAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_w
{
template <class ContainerAllocator>
struct omegaRequest_
{
  typedef omegaRequest_<ContainerAllocator> Type;

  omegaRequest_()
    : radius(0.0)  {
    }
  omegaRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef float _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::hello_w::omegaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_w::omegaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct omegaRequest_

typedef ::hello_w::omegaRequest_<std::allocator<void> > omegaRequest;

typedef boost::shared_ptr< ::hello_w::omegaRequest > omegaRequestPtr;
typedef boost::shared_ptr< ::hello_w::omegaRequest const> omegaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_w::omegaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_w::omegaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_w

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::omegaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::omegaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::omegaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::omegaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::omegaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::omegaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_w::omegaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b690044065f2210effb664cc7a28125";
  }

  static const char* value(const ::hello_w::omegaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b690044065f2210ULL;
  static const uint64_t static_value2 = 0xeffb664cc7a28125ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_w::omegaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_w/omegaRequest";
  }

  static const char* value(const ::hello_w::omegaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_w::omegaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 radius\n"
;
  }

  static const char* value(const ::hello_w::omegaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_w::omegaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct omegaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_w::omegaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_w::omegaRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_W_MESSAGE_OMEGAREQUEST_H
