// Generated by gencpp from file hello_w/omega.msg
// DO NOT EDIT!


#ifndef HELLO_W_MESSAGE_OMEGA_H
#define HELLO_W_MESSAGE_OMEGA_H

#include <ros/service_traits.h>


#include <hello_w/omegaRequest.h>
#include <hello_w/omegaResponse.h>


namespace hello_w
{

struct omega
{

typedef omegaRequest Request;
typedef omegaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct omega
} // namespace hello_w


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_w::omega > {
  static const char* value()
  {
    return "5415f591ce3216ca03d8f91dffc8ffed";
  }

  static const char* value(const ::hello_w::omega&) { return value(); }
};

template<>
struct DataType< ::hello_w::omega > {
  static const char* value()
  {
    return "hello_w/omega";
  }

  static const char* value(const ::hello_w::omega&) { return value(); }
};


// service_traits::MD5Sum< ::hello_w::omegaRequest> should match 
// service_traits::MD5Sum< ::hello_w::omega > 
template<>
struct MD5Sum< ::hello_w::omegaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_w::omega >::value();
  }
  static const char* value(const ::hello_w::omegaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_w::omegaRequest> should match 
// service_traits::DataType< ::hello_w::omega > 
template<>
struct DataType< ::hello_w::omegaRequest>
{
  static const char* value()
  {
    return DataType< ::hello_w::omega >::value();
  }
  static const char* value(const ::hello_w::omegaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_w::omegaResponse> should match 
// service_traits::MD5Sum< ::hello_w::omega > 
template<>
struct MD5Sum< ::hello_w::omegaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_w::omega >::value();
  }
  static const char* value(const ::hello_w::omegaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_w::omegaResponse> should match 
// service_traits::DataType< ::hello_w::omega > 
template<>
struct DataType< ::hello_w::omegaResponse>
{
  static const char* value()
  {
    return DataType< ::hello_w::omega >::value();
  }
  static const char* value(const ::hello_w::omegaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_W_MESSAGE_OMEGA_H
