// Generated by gencpp from file hello_w/stateRequest.msg
// DO NOT EDIT!


#ifndef HELLO_W_MESSAGE_STATEREQUEST_H
#define HELLO_W_MESSAGE_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_w
{
template <class ContainerAllocator>
struct stateRequest_
{
  typedef stateRequest_<ContainerAllocator> Type;

  stateRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , w(0.0)  {
    }
  stateRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::hello_w::stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_w::stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stateRequest_

typedef ::hello_w::stateRequest_<std::allocator<void> > stateRequest;

typedef boost::shared_ptr< ::hello_w::stateRequest > stateRequestPtr;
typedef boost::shared_ptr< ::hello_w::stateRequest const> stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_w::stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_w::stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_w

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_w::stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_w::stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_w::stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_w::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48f455a89ab93be67e87c19e07e9aa3d";
  }

  static const char* value(const ::hello_w::stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48f455a89ab93be6ULL;
  static const uint64_t static_value2 = 0x7e87c19e07e9aa3dULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_w::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_w/stateRequest";
  }

  static const char* value(const ::hello_w::stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_w::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"float32 v\n"
"float32 w\n"
;
  }

  static const char* value(const ::hello_w::stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_w::stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_w::stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_w::stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_W_MESSAGE_STATEREQUEST_H
