// Generated by gencpp from file hello_w/state.msg
// DO NOT EDIT!


#ifndef HELLO_W_MESSAGE_STATE_H
#define HELLO_W_MESSAGE_STATE_H

#include <ros/service_traits.h>


#include <hello_w/stateRequest.h>
#include <hello_w/stateResponse.h>


namespace hello_w
{

struct state
{

typedef stateRequest Request;
typedef stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct state
} // namespace hello_w


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_w::state > {
  static const char* value()
  {
    return "a371dbc8e48639d98b2f53f083975699";
  }

  static const char* value(const ::hello_w::state&) { return value(); }
};

template<>
struct DataType< ::hello_w::state > {
  static const char* value()
  {
    return "hello_w/state";
  }

  static const char* value(const ::hello_w::state&) { return value(); }
};


// service_traits::MD5Sum< ::hello_w::stateRequest> should match 
// service_traits::MD5Sum< ::hello_w::state > 
template<>
struct MD5Sum< ::hello_w::stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_w::state >::value();
  }
  static const char* value(const ::hello_w::stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_w::stateRequest> should match 
// service_traits::DataType< ::hello_w::state > 
template<>
struct DataType< ::hello_w::stateRequest>
{
  static const char* value()
  {
    return DataType< ::hello_w::state >::value();
  }
  static const char* value(const ::hello_w::stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_w::stateResponse> should match 
// service_traits::MD5Sum< ::hello_w::state > 
template<>
struct MD5Sum< ::hello_w::stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_w::state >::value();
  }
  static const char* value(const ::hello_w::stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_w::stateResponse> should match 
// service_traits::DataType< ::hello_w::state > 
template<>
struct DataType< ::hello_w::stateResponse>
{
  static const char* value()
  {
    return DataType< ::hello_w::state >::value();
  }
  static const char* value(const ::hello_w::stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_W_MESSAGE_STATE_H
